# Generated by Django 4.1.5 on 2023-04-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45, unique=True)),
                ('city_intro', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=50, unique=True)),
                ('hotel_address', models.CharField(max_length=50, unique=True)),
                ('hotel_website', models.CharField(blank=True, default='', max_length=50)),
                ('hotel_cost_per_night', models.CharField(default='', max_length=50)),
                ('introduction', models.CharField(max_length=600, unique=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='sichuaninfo.city')),
            ],
            options={
                'ordering': ['hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=45)),
                ('route_detail', models.CharField(max_length=450)),
            ],
            options={
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('zoo_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50, unique=True)),
                ('attraction_name', models.CharField(max_length=50, unique=True)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600, unique=True)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=50)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoos', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=45)),
                ('restaurant_address', models.CharField(max_length=50)),
                ('restaurant_tel', models.IntegerField(blank=True, default='')),
                ('restaurant_history', models.CharField(max_length=600, unique=True)),
                ('cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['restaurant_name'],
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50, unique=True)),
                ('attraction_name', models.CharField(max_length=50, unique=True)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600, unique=True)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=50)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='museums', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('monument_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50, unique=True)),
                ('attraction_name', models.CharField(max_length=50, unique=True)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600, unique=True)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=50)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monuments', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('mall_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50, unique=True)),
                ('attraction_name', models.CharField(max_length=50, unique=True)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600, unique=True)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=50)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='malls', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.CreateModel(
            name='LocalFav',
            fields=[
                ('localfav_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50, unique=True)),
                ('attraction_name', models.CharField(max_length=50, unique=True)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600, unique=True)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=50)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localfavs', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='route',
            field=models.ManyToManyField(blank=True, to='sichuaninfo.route'),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=20)),
                ('course_history', models.CharField(max_length=600)),
                ('restaurant', models.ManyToManyField(blank=True, to='sichuaninfo.restaurant')),
            ],
            options={
                'ordering': ['cuisine_name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='route',
            field=models.ManyToManyField(blank=True, to='sichuaninfo.route'),
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('bar_id', models.AutoField(primary_key=True, serialize=False)),
                ('attraction_address', models.CharField(max_length=50)),
                ('attraction_name', models.CharField(max_length=50)),
                ('attraction_website', models.CharField(blank=True, default='', max_length=100)),
                ('attraction_introduction', models.CharField(max_length=600)),
                ('attraction_tel', models.CharField(blank=True, default='', max_length=30)),
                ('attraction_cost', models.CharField(blank=True, default='', max_length=50)),
                ('suggest_duration', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='sichuaninfo.city')),
                ('hotel', models.ManyToManyField(blank=True, to='sichuaninfo.hotel')),
                ('route', models.ManyToManyField(blank=True, to='sichuaninfo.route')),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
    ]
