# Generated by Django 4.1.5 on 2023-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sichuaninfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_history',
            field=models.CharField(max_length=600),
        ),
    ]
