# Generated by Django 4.1.5 on 2023-04-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sichuaninfo', '0002_alter_restaurant_restaurant_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_intro',
            field=models.CharField(max_length=1500, unique=True),
        ),
    ]
