# Generated by Django 4.1.5 on 2023-04-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sichuaninfo', '0004_alter_bar_attraction_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuisine', to='sichuaninfo.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_tel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
