# Generated by Django 4.1.5 on 2023-05-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sichuaninfo', '0008_alter_restaurant_restaurant_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='course_history',
            new_name='cuisine_history',
        ),
    ]
